### ISSUE TITLE
What should I change in parameters if I track object with following states [left, top, width/height, height]

### ISSUE THREAD

**Issue by JohnPekl** [phquentin/lmb_tracker#31]
Your code tracks objects with two states (center x & y). I want to track a bounding box with the following states _[left, top, width/height, height]_. **width/height** is considered as the ratio of a bounding box. How can I change initial parameters such as process noise covariance, existence probability pruning threshold, etc?

**Comment by phquentin** [comment]
Hi John, 
at the moment the measurement model within the code is not suitable for bounding boxes. We will implement a corresponding measurement model for 2D and 3D bounding boxes within the next months.
